### ISSUE TITLE
React Helmet error

### ISSUE THREAD

**Issue by aladearchives** [PacktPublishing/React-Projects#10]
I was getting below error when I use the latest react version along with react Helmet.
`Attempted import error: 'react-helmet' does not contain a default export (imported as 'Helmet').
`
Their updated documentation says the module should be imported as:

`import {Helmet} from "react-helmet";
`
That should fix the error. Would need to update the code on all Components that are using Helmet including the Header, Question and Field Components.

**Comment by royderks** [comment]
Hi @aladearchives, I would advise using the version of react-helmet that you can find in the `package.json` file of the chapter you're working in
