### ISSUE TITLE
Moving through Ch1 but not having success.   Where is reference source?

### ISSUE THREAD

**Issue by fogdog2020** [PacktPublishing/React-Projects#13]
Spending a lot of time just trying to get through Ch1.   There are several errors that I have worked through (typos on pg. 12 and 22) and moving the media directory to the root, but I am now left with a significant investment of time but still no joy.   

The book implies on page 8 that there is "The complete code for this chapter can be found on GitHub.." but this seems to be incorrect.   Where can I find the working source that I might check my work against?  I seem to be running into the same mistake or error over and over and no longer feel that repeating this in step-by-step pieces (with the same failed result) is no longer helping my learning or confidence in being able to continue.   Any help/insight appreciated!

**Comment by utkarsha-Packt** [comment]
Hello 

You can find the code files by clicking on the master tab. There you'll find all the code files. Let me know if it helps.
