### ISSUE TITLE
Chapter 3.  onDrop issue.  Final code didn't match due to matching lane vs board.  This site had correct code

### ISSUE THREAD

**Issue by durrantm** [PacktPublishing/React-Projects#15]
In `Board.js`, for `onDragOver` the chapter uses

`ticket.board = boardId` at the end of the chapter

However the code in this repo uses 

`ticket.lane = laneId` as the chapter end state code

The repo code is correct and works ok.

So unless I missed it, the book code at the end of the chapter is wrong for chapter final state

**Comment by sohamapackt** [comment]
@durrantm Thanks for the update
