### ISSUE TITLE
'MODULE_NOT_FOUND'

### ISSUE THREAD

**Issue by danielbulican** [PacktPublishing/React-Projects#20]
Hello,

I just started with the movie list app and I installed the webpack-dev-server packages, before the installation of this package I could easily open the app in the browser with npm start. After the installation of webpack-dev-server, however, this is no longer possible because of this error. I really appreciate your help

Error: Cannot find module 'webpack-cli/bin/config-yargs'
Require stack:
- C:\Users\User\Documents\movieList\node_modules\webpack-dev-server\bin\webpack-dev-server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\User\Documents\movieList\node_modules\webpack-dev-server\bin\webpack-dev-server.js:65:1)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\User\\Documents\\movieList\\node_modules\\webpack-dev-server\\bin\\webpack-dev-server.js'
  ]
}

**Comment by Chateau03** [comment]
try this way, it worked for me:
"start": "webpack serve --mode development",
instead of using:
"start": "webpack-dev-server --mode development --open"

**Comment by danielbulican** [comment]
> try this way, it worked for me:
> "start": "webpack serve --mode development",
> instead of using:
> "start": "webpack-dev-server --mode development --open"

Thank you, it did work. It is interesting that it opens in http://localhost:8080/. I wonder why, can you explain it to me please?

**Comment by Chateau03** [comment]
> > try this way, it worked for me:
> > "start": "webpack serve --mode development",
> > instead of using:
> > "start": "webpack-dev-server --mode development --open"
> 
> Thank you, it did work. It is interesting that it opens in http://localhost:8080/. I wonder why, can you explain it to me please?

well, doing some research I found that it is a default port of webpack, I also found that it can be configured to start from another port but the truth is I am quite new in this too 😂

**Comment by sonam-packt** [comment]
Thank you Chateau for the help!

**Comment by danielbulican** [comment]
It makes sense now, your efforts are really appreciated 


Sent from Yahoo Mail for iPhone


On Tuesday, October 27, 2020, 3:33 PM, Raúl A. Castillo G. <notifications@github.com> wrote:






try this way, it worked for me:
"start": "webpack serve --mode development",
instead of using:
"start": "webpack-dev-server --mode development --open"


Thank you, it did work. It is interesting that it opens in http://localhost:8080/. I wonder why, can you explain it to me please?


well, doing some research I found that it is a default port of webpack, I also found that it can be configured to start from another port but the truth is I am quite new in this too 😂
