### ISSUE TITLE
[ESLint] App was running OK until ESLint installed

### ISSUE THREAD

**Issue by armaanreza** [PacktPublishing/React-Projects#3]
As soon as I did "npm install --save-dev eslint eslint-loader eslint-plugin-react"; the app broke.

Here is the error:

` npm start

> movieList@1.0.0 start C:\Users\Reza\home\movieList
> webpack-dev-server --mode development --open

× ｢wds｣: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module.rules[0].use should be one of these:
   non-empty string | function | object { ident?, loader?, options?, query? } | function | [non-empty string | function | object { ident?, loader?, options?, query? }]
   -> Modifiers applied to the module when rule is matched
   Details:
    * configuration.module.rules[0].use.loader should be a string.
    * configuration.module.rules[0].use.loader should be one of these:
      non-empty string
      -> Loader name
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! movieList@1.0.0 start: `webpack-dev-server --mode development --open`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the movieList@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Reza\AppData\Roaming\npm-cache\_logs\2020-01-04T15_40_51_618Z-debug.log`

I greatly appreciate @royderks  input on above.

**Comment by royderks** [comment]
Thank you for reaching out @armaanreza! Can you share a link to the code of the application at the moment that you receive this error?

Can you also check that after installing these packages you've updated Webpack as described in step 3 on page 31?

**Comment by armaanreza** [comment]
Thank you @royderks for your response. Here is the link of my repo:
[https://github.com/armaanreza/movieList/tree/codes](url)

 I have updated the Webpack config file as stated in step 3, but the error still persist.

Regards

**Comment by royderks** [comment]
Hi @armaanreza, I've found the issue in your code:

After installing `eslint-loader` you need to change the following line in `webpack.config.js` from:
```js
use: {
  loader: 'babel-loader'
}
```
to:
```js
use: ['babel-loader', 'eslint-loader'],
```
This is shown on page 31 in step 3.

The reason for this is that when you want to use an array of loaders, the `use` field must be an array as well. If you have an object for `use` with an array for the field `loader` your code will break as Webpack can't handle defining the loaders like this.

Let me know if this fixes the issue for you :)

**Comment by armaanreza** [comment]
Hi @royderks, thank you so much! It's resolved. I really appreciate your time and support to review my codes and pointing out to the error! This feels good and motivated me to continue with your book.
