### ISSUE TITLE
Chapter 4 node server issue

### ISSUE THREAD

**Issue by MarkellRichards** [PacktPublishing/React-Projects#4]
Hello Roy,

I am getting the following errors in the browser when I run npm run ssr:

Uncaught SyntaxError: Unexpected token '<'
main.944e8127.chunk.js:1 Uncaught SyntaxError: Unexpected token '<'
manifest.json:1 Manifest: Line: 1, column: 1, Syntax error.

Also in the console, I get the following errors:

Warning: componentWillMount has been renamed, and is not recommended for use. 
See https://fb.me/react-unsafe-component-lifecycles for details.

* Move code from componentWillMount to componentDidMount (preferred in most cases) or the constructor.

Please update the following components: SideEffect(NullComponent)

***********************************************************************

I thought perhaps I was mistyping something when following along. However, I downloaded the completed version, ran npm install, npm run build, and npm run ssr and got the same errors. Any help with this issue is appreciated.

The client-side works just fine.

**Comment by royderks** [comment]
Hi @MarkellRichards, thanks for submitting this issue! The problem you're facing got into the code in this commit https://github.com/PacktPublishing/React-Projects/commit/65ddbd9daa3b474f10259b439a91fb264d374515#diff-ea75b530d74f94670cea053feb8b961b for the `node/server.js` file. I'm trying to narrow down your issue and fix it ASAP!

**Comment by sa-ma** [comment]
I'm also having the same issue

**Comment by royderks** [comment]
Thank you for commenting, I'm trying to find a solution **ASAP**!

**Comment by royderks** [comment]
Hi @MarkellRichards, @sa-ma. I've requested to make a revision to the chapter with the publisher, will discuss how to handle this issue and get the revised chapter to you

**Comment by ahajji87** [comment]
I solved adding this line after initialise of app in server.js
```
const app = express();
// add this
app.use(express.static('./build'));
```

**Comment by cjolaguera** [comment]
this one worked for me as well

> I solved adding this line after initialise of app in server.js
> 
> ```
> const app = express();
> // add this
> app.use(express.static('./build'));
> ```

**Comment by royderks** [comment]
Thanks for helping with finding a solution @ahajji87, I've updated the code with your input
