### ISSUE TITLE
Chapter 1 - Assets and Media shouldn't be in src folder

### ISSUE THREAD

**Issue by ericchuawc** [PacktPublishing/React-Projects#5]
Both Assets and Media should be outside of src folder

In your book

![Screenshot 2020-01-31 at 12 45 29 AM](https://user-images.githubusercontent.com/24249779/73470644-29f7a280-43c3-11ea-882e-2607075bc670.png)

I have to manually move them out to be same level with src folder.. else will have broken images and missing data.json file.

**Comment by kennethbernstrom** [comment]
I also struggled with a 404 on the assets when following the folder structure in the book. But when i moved both the assets and media folder up to the root it worked! Thanks...

**Comment by ericchuawc** [comment]
it seems the "tree" screenshots not so tally.. I also faced the same issue on the "github portfolio app" chapter.. i reckon to tally your screenshots

**Comment by ttn2001** [comment]
I had this exact issue when following the tutorial, kept getting a 404 error.

**Comment by royderks** [comment]
Thanks for resolving this issue @ericchuawc, the screenshot seems to be incorrect indeed. I've requested this change with the publisher.
