### ISSUE TITLE
Chapter 4 willMount to did Mount

### ISSUE THREAD

**Issue by Puzanira** [PacktPublishing/React-Projects#8]
Hello
Thank you for your book!

I've installed the last version of ch4, run `npm run build` and `npm run ssr` and got this issue:
 ```
Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles f
or details.

* Move code from componentWillMount to componentDidMount (preferred in most cases) or the constructor.

Please update the following components: SideEffect(NullComponent)
```

No mentions of `componentWillMount` found in the source code, usage found in node_modules
App is working, but showing *Loading..* all the time.
Any ideas how to fix that?

**Comment by royderks** [comment]
Hi @Puzanira, Thanks for filing an issue. The error you're showing is coming from one of the dependencies, and is unrelated to the problem you're having. Please refer to https://github.com/PacktPublishing/React-Projects/issues/4 for your issue, as I've requested to rewrite the contents of chapter 4 at the publisher.
