### ISSUE TITLE
Chp 7. TypeError: this.client.watchQuery is not a function

### ISSUE THREAD

**Issue by robin-howland** [PacktPublishing/React-Projects#9]
This publication is riddled with errors. So far not a single chapter has been error free.

Latest one, having made changes up to & including page 225 and expecting to see the products returned.

```
TypeError: this.client.watchQuery is not a function

Query.initializeQueryObservable
/src/Query.tsx:274

  271 |     this.queryObservable = this.context.renderPromises.getSSRObservable(this);
  272 |   }
  273 |   if (!this.queryObservable) {
> 274 |     this.queryObservable = this.client.watchQuery(opts);
      | ^  275 |   }
  276 | }
  277 | 
```

**Comment by royderks** [comment]
Hi @robin-howland, sorry to hear you're having some issues. This error seems to be coming from one of the dependencies, `react-apollo`. I've locked all the dependencies in https://github.com/PacktPublishing/React-Projects/commit/b317eabae82eac2f48bd8e655692d6cbb7b90b46, to prevent your package manager from installing an unsupported version.
